name: bestmovies
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: 0.12.0+4
  equatable: ^1.1.1
  get_it: ^4.0.2
  simple_animations: ^2.2.1
  styled_widget: ^0.2.1+2
  flutter_bloc: ^4.0.0
  json_annotation: ^3.0.0
  flutter:
    sdk: flutter



dev_dependencies:
  build_runner: ^1.8.1
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true